env:
  browser: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - off
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
