version: '3.9'
services:
  kana:
    container_name: kana
    build: .
    restart: on-failure
    environment:
      - NODE_ENV="production"
    env_file: 
      - .env
    volumes:
      - .:/kana
  lavalink:
    container_name: lavalink
    image: ghcr.io/freyacodes/lavalink:latest
    ports:
      - 2333:2333
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
