name: Build Docker image and publish
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'package*.json'
      - 'Dockerfile'
      - '.github/workflows/build.yml'
    paths-ignore:
      - '!src/commands/**'
      - '!src/listeners/**'
      - '!src/preconditions/**' 
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build image
        run: |
          docker build . --tag ghcr.io/thaddeuskkr/kana:dev --tag ghcr.io/thaddeuskkr/kana:${{ vars.GITHUB_SHA }}
          docker push ghcr.io/thaddeuskkr/kana:dev
          docker push ghcr.io/thaddeuskkr/kana:${{ vars.GITHUB_SHA }}

